name: freemework_http
description: HTTP related classes of the Freemework
version: 0.2.0
homepage: https://freemework.org
repository: https://github.com/freemework/dart.http
issue_tracker: https://github.com/freemework/dart.http/issues
documentation: https://freemework.org/#http?lang=dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freemework: ^0.2.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  freemework_cancellation: ^0.2.0
  pedantic: ^1.11.1
  test: ^1.20.1
