name: freemework_http
description: Freemework
version: 0.0.1
homepage: https://freemework.org

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  freemework:
    path: ../freemework.dart

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  pedantic: ^1.9.2
  test: ^1.15.7
