name: freemework_http
description: HTTP related classes of the Freemework
version: 0.0.1
homepage: https://freemework.org
repository: https://github.com/freemework/dart.http
issue_tracker: https://github.com/freemework/dart.http/issues
documentation: https://freemework.org/#http?lang=dart

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  freemework: ^0.0.1
  http: ^0.12.2

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  freemework_cancellation: ^0.0.1
  pedantic: ^1.9.2
  test: ^1.15.7
